In [6]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 300)
from collections import Counter

In [7]:
df_95 = pd.read_csv('1995_Street_Tree_Census.csv')

In [8]:
df_05 = pd.read_csv('2005_Street_Tree_Census.csv', low_memory=False)

In [9]:
df_15 = pd.read_csv('2015StreetTreesCensus_TREES.csv')

In [ ]:
## Trees 95

In [7]:
df_95.head(4)

,RecordId,Address,House_Number,Street,Postcode_Original,Community Board_Original,Site,Species,Diameter,Condition,Wires,Sidewalk_Condition,Support_Structure,Borough,X,Y,Longitude,Latitude,CB_New,Zip_New,CensusTract_2010,CensusBlock_2010,NTA_2010,SegmentID,Spc_Common,Spc_Latin,Location,Council District,BIN,BBL
0,1,245 E 17 ST,245.0,E 17 ST,10003,106,Front,PLAC,8,Unknown,None,NaN,None,Manhattan,988618.9688,206893.7640,-73.984235,40.734551,106,10003,48.0,2000.0,MN21,33134,LONDON PLANETREE,PLATANUS ACERIFOLIA,"(40.734551, -73.984235)",2.0,1019566.0,1.008980e+09
1,2,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,7,Good,None,Good,None,Manhattan,981330.4271,201649.9518,-74.010532,40.720159,101,10013,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09
2,3,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,6,Good,None,Good,None,Manhattan,981330.4271,201649.9518,-74.010532,40.720159,101,10013,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09
3,4,80 N MOORE ST,80.0,N MOORE ST,10013,101,Side,ACPL,7,Excellent,None,Good,None,Manhattan,981330.4271,201649.9518,-74.010532,40.720159,101,10013,39.0,2001.0,MN24,31567,"MAPLE, NORWAY",ACER PLATANOIDES,"(40.720159, -74.010532)",1.0,1083157.0,1.001420e+09

In [43]:
df_95.Borough.unique()

array(['Manhattan', 'Bronx', 'Brooklyn', 'Queens', 'Staten Island'],
      dtype=object)

In [132]:
pd.value_counts(df_95['Condition'])

Good              332562
Excellent         100286
Poor               38571
Planting Space     15231
Dead               12859
Unknown            10761
Stump               6087
Fair                 327
Shaft                303
Critical               2
Name: Condition, dtype: int64

In [23]:
species_95 = list(df_95.Spc_Common.unique())

In [25]:
len(species_95)

276

In [122]:
df_95_species = pd.DataFrame(pd.value_counts(df_95['Spc_Common']))

In [126]:
df_95_sci = pd.DataFrame(pd.value_counts(df_95['Spc_Latin']))

In [125]:
len(df_95_species)

276

In [127]:
len(df_95_sci)

263

In [130]:
df_95_species.head(276)

                      Spc_Common
MAPLE, NORWAY             109321
LONDON PLANETREE           88040
OAK, PIN                   36553
HONEYLOCUST                33727
PEAR, CALLERY              31293
LINDEN, LITTLE LEAF        26489
MAPLE, SILVER              22347
MAPLE, RED                 17993
ASH, GREEN                 17684
MAPLE, SUGAR               15355
PLANTING SITE              15231
GINKGO                     13758
UNKNOWN LIVE TREES         10944
JAPANESE PAGODA TREE        8581
MAPLE, SYCAMORE             7592
UNKNOWN DEAD TREES          6833
OAK, NORTHERN RED           6713
SWEETGUM                    6671
ELM, AMERICAN               6057
ZELKOVA, JAPANESE           5740
UNKNOWN STUMP               4165
CHERRY, CORNELIAN           2592
TREE OF HEAVEN              2476
OAK, WILLOW                 1964
PINE, OTHER                 1363
STUMP                       1232
EASTERN HOP HORNBEAM        1104
HACKBERRY                   1007
HORSECHESTNUT                863
CHERRY, BLACK                816
BLACKGUM                     811
MAPLE, OTHER                 808
CHERRY, OTHER                733
HAWTHORN, OTHER              622
APPLE                        499
LINDEN, OTHER                474
BIRCH, OTHER                 427
MAPLE, JAPANESE              420
BLACK LOCUST                 385
TULIP TREE                   340
ELM, OTHER                   332
OAK, OTHER                   314
MULBERRY, RED                271
MULBERRY, WHITE              235
SPRUCE, OTHER                224
DOGWOOD, OTHER               223
CATALPA, SOUTHERN            215
FIR, OTHER                   198
OAK, WHITE                   193
HEMLOCK, EASTERN             188
CRABAPPLE                    174
ASH, OTHER                   165
MAGNOLIA, OTHER              151
CATALPA, NORTHERN            150
YEW                          145
UNKNOWN SHAFT                142
HAWTHORN, WASHINGTON         139
BEECH, OTHER                 127
PINE, EASTERN WHITE          119
PLUM, AMERICAN               114
MIMOSA                       109
PINE, AUSTRIAN                97
LINDEN, AMERICAN              95
CEDAR, ATLAS                  93
OAK, ENGLISH                  87
SPRUCE, NORWAY                83
POPLAR, OTHER                 70
COTTONWOOD, EASTERN           69
SASSAFRAS                     68
DOGWOOD, FLOWERING            68
WILLOW SPECIES                66
CHERRY, KWANZAN               61
HOLLY SPECIES                 60
LINDEN, SILVER                57
ELM, CHINESE                  55
PEAR, COMMON                  53
OAK, CHESTNUT                 51
HORSECHESTNUT, RED            51
ASH, WHITE                    50
PLUM, PURPLELEAF              48
CEDAR, DEODAR                 48
PEACH                         46
PINE, SPRUCE                  45
CHERRY, HIGAN-PENDLA          38
WILLOW, WEEPING               36
BIRCH, GRAY                   35
LOQUAT                        35
SPRUCE, COLORAD BLUE          33
HICKORY, OTHER                32
ROSE-OF-SHARON                32
CYPRESS, LEYLAND              32
POPLAR, BALSAM                29
ARBORVITAE, AMERICAN          28
MAGNOLIA, STAR                27
WALNUT, BLACK                 25
PINE, SHORTLEAF               24
PLUM, FLOWERING               24
PINE, JAPANESE BLACK          24
BEECH, AMERICAN               24
BOXELDER                      23
MAPLE, STRIPED                23
OAK, SCARLET                  22
HOLLY, AMERICAN               22
MAPLE, BLACK                  21
ATLANTIC WHITE CEDAR          21
BIRCH, PAPER                  20
SPRUCE, COLORADO              20
POPLAR, GRAY                  20
EASTERN REDCEDAR              20
OAK, BLACK                    20
MAPLE, HEDGE                  18
CRABAPPLE-HARV. GOLD          18
BIRCH, EUROPEAN               18
MAPLE, AMUR                   17
BIRCH, RIVER                  17
ALDER, EUROPEAN               16
OAK, SILK                     16
CHERRY, PIN                   16
CHERRY, SARGENT               16
REDWOOD, COAST                16
PINE, NORFOLK ISLAND          16
AMERICAN SYCAMORE             15
AMUR CORKTREE                 15
OAK, SAWTOOTH                 15
MAGNOLIA, SAUCER              15
BEECH, EUROPEAN               15
CHINABERRY                    15
CHOKECHERRY, AMUR             14
HORNBEAM, AMERICAN            13
CHINESE PISTACHE              13
SPRUCE, BLACK                 12
DOGWOOD, KOUSA                12
ASPEN, QUAKING                12
ZELKOVA                       12
HICKORY, BLACK                11
DAWN REDWOOD                  11
ILEX                          11
SHRUB                         10
SERVICEBERRY, OTHER           10
ELM, SIBERIAN                 10
EASTERN REDBUD                10
HEDGE                         10
PINE, PITCH                   10
LARCH, COMMON                 10
WILLOW, BLACK                  9
BALDCYPRESS                    9
GOLDENRAIN TREE                9
PINE, SAND                     9
ROYAL PAULOWNIA                9
REDWOOD, GIANT                 8
PALM, OTHER                    8
PINE, POND                     8
MAPLE, SUGAR-GRN MTN           8
SERVICEBERRY, DOWNY            8
HORNBEAM, EUROPEAN             8
ROSE SPECIES                   8
POPLAR, LOMBARDY               7
DOUGLAS FIR                    7
SPRUCE, WHITE                  7
ASPEN, BIGTOOTH                7
HOLLY, DAHOON                  7
ASH, FLOWERING                 7
TRUMPET TREE SP                7
ASH, ARIZONA                   7
CHOKECHERRY, COMMON            6
HICKORY, MOCKERNUT             6
ACACIA, SWEET                  6
OLIVE, AUTUMN                  6
OAK, LIVE                      6
SUGARBERRY                     6
COTTONWOOD, BLACK              6
HONEYSUCKLE                    6
CRABAPPLE-IND.SUMMER           6
ELM, SEPTEMBER (RED)           5
BAYBERRY, EVERGREEN            5
ACACIA, EARLEAF                5
KENTUCKY COFFEETREE            5
FIR, BALSAM                    5
MAPLE, RED-RED SUNST           5
BIRCH, SWEET                   5
MOUNTAIN-ASH, EURO.            5
BAYBERRY, SOUTHERN             5
JAPANESE CEDAR                 5
ELM, WINGED                    5
CHESTNUT, CHINESE              5
HICKORY, BITTERNUT             4
HICKORY, SHELLBARK             4
CHINESE TALLOW                 4
BIRCH, WEEPING                 4
WILLOW, CORKSCREW              4
OAK, BLACKJACK                 4
OAK, SHUMARD                   4
FIG, BENJAMIN                  4
MAGNOLIA, CHINESE              4
MAPLE, TRIDENT                 3
MOUNTAIN-ASH, AMER.            3
HICKORY, PIGNUT                3
OLIVE, RUSSIAN                 3
FIR, WHITE                     3
RED BAY                        3
CAMPHOR                        3
BUTTERNUT                      3
ELM, ENGLISH                   3
CHINKAPIN, ALLEGHENY           3
HIBISCUS                       3
PINE, JACK                     3
ELM, CEDAR                     3
WALNUT, ENGLISH                3
ELM, SLIPPERY                  2
MONKEY PUZZLE TREE             2
CRANBERRY, AMERICAN            2
MAPLE, NORWAY-SCHWED           2
ARBORVITAE, WESTERN            2
PAWPAW                         2
BUCKEYE, YELLOW                2
PRUNUS                         2
PINE, AUSTRALIAN               2
CHINESE PARASOL TREE           2
PEAR, CALLERY-ARISTO           2
CHERRY, MAZZARD                2
OAK, POST                      2
APRICOT                        2
OAK, SWAMP WHITE               2
HAWTHORN, GREEN                2
ELM, ROCK                      2
COTTONWOOD, SWAMP              2
MAPLE, NORWAY-CR KNG           2
BUCKEYE, OHIO                  2
PAPER MULBERRY                 2
LAURELCHERRY, CAROLI           2
MAGNOLIA, SOUTHERN             2
PRIVET, CHINESE                2
FIG, RUSTYLEAF                 2
OAK, BASTARD                   1
OAK, OVERCUP                   1
HICKORY, SHAGBARK              1
HAZEL SPECIES                  1
SOURWOOD                       1
ASH, WHITE-AUT PURPL           1
OAK, SOUTHERN RED              1
PINE, RED                      1
POPLAR, WHITE                  1
PALM, PAUROTIS                 1
OAK, CHINKAPIN                 1
FIG, COMMON                    1
PINE, SCOTCH                   1
ASH, BLUE                      1
YELLOWOOD                      1
BOTTLEBRUSH                    1
GOLDENRAIN TREE, S             1
CABBAGE PALMETTO               1
EUR. SMOKE TREE                1
HAWTHORN, COCKSPUR             1
MAPLE, ARMSTRONG               1
SCHEFFLERA                     1
FRANGIPANI                     1
PERSIMMON, COMMON              1
DATE PALM                      1
ASH, EUROPEAN                  1
FIG, FLA. STRANGLER            1
MAPLE, RED-OCT GLORY           1
HAWTHORN, PARSLEY              1
BUTTONWOOD, SILVER             1
KATSURA TREE                   1
PRIVET SPECIES                 1
WITCH HAZEL                    1
BIRCH, YELLOW                  1
WILLOW, LAUREL                 1
OAK, BUR                       1
OAK, BLUEJACK                  1
BISCHOFIA                      1
ASH, GREEN-MARS SEED           1
ARBORVITAE, ORIENTAL           1
PONGAM                         1
PLUM, JAMBOLAN                 1
GOLDEN-CHAIN TREE              1

In [131]:
df_95_sci.head(263)

                              Spc_Latin
ACER PLATANOIDES                 109325
PLATANUS ACERIFOLIA               88040
QUERCUS PALUSTRIS                 36553
GLEDITSIA TRIACANTHOS             33727
PYRUS CALLERYANA                  31295
TILIA CORDATA                     26489
ACER SACCHARINUM                  22347
ACER RUBRUM                       18000
FRAXINUS PENNSYLVANICA            17685
ACER SACCHARUM                    15363
PLANTING SITE                     15231
GINKGO BILOBA                     13758
UNKNOWN LIVE TREES                10944
SOPHORA JAPONICA                   8581
ACER PSEUDOPLATANUS                7592
UNKNOWN DEAD TREES                 6833
QUERCUS RUBRA                      6713
LIQUIDAMBAR STYRACIFLUA            6671
ULMUS AMERICANA                    6057
ZELKOVA SERRATA                    5740
UNKNOWN STUMP                      3388
CORNUS MAS                         2592
AILANTHUS ALTISSIMA                2476
QUERCUS PHELLOS                    1964
PINUS SPECIES                      1363
STUMP                              1232
OSTRYA VIRGINIANA                  1104
CELTIS OCCIDENTALIS                1007
AESCULUS HIPPOCASTANUM              863
PRUNUS SEROTINA                     816
NYSSA SYLVATICA                     811
ACER SPECIES                        808
UNKNOWN STUMP                       777
PRUNUS SPECIES                      735
CRATAEGUS SPECIES                   622
MALUS PUMILA                        499
TILIA SPECIES                       474
BETULA SPECIES                      427
ACER PALMATUM                       420
ROBINIA PSEUDOACACIA                385
LIRIODENDRON TULIPIFERA             340
ULMUS SPECIES                       332
QUERCUS SPECIES                     314
MORUS RUBRA                         271
MORUS ALBA                          235
PICEA SPECIES                       224
CORNUS SPECIES                      223
CATALPA BIGNONIOIDES                215
MALUS SPECIES                       198
ABIES SPECIES                       198
QUERCUS ALBA                        193
TSUGA CANADENSIS                    188
FRAXINUS SPECIES                    165
MAGNOLIA SPECIES                    151
CATALPA SPECIOSA                    150
TAXUS SPECIES                       145
CRATAEGUS PHAENOPYRUM               139
FAGUS SPECIES                       127
UNKNOWN SHAFT                       120
PINUS STROBUS                       119
PRUNUS AMERICANA                    114
ALBIZIA JULIBRISSIN                 109
PINUS NIGRA                          97
TILIA AMERICANA                      95
CEDRUS ATLANTICA                     93
QUERCUS ROBUR                        87
PICEA ABIES                          83
ILEX SPECIES                         71
POPLAR SPECIES                       70
POPULUS DELTOIDES                    69
SASSAFRAS ALBIDUM                    68
CORNUS FLORIDA                       68
SALIX SPECIES                        66
PRUNUS SERRULATA                     61
TILIA TOMENTOSA                      57
ULMUS PARVIFOLIA                     55
PICEA PUNGENS                        53
PYRUS COMMUNIS                       53
AESCULUS X CARNEA                    51
QUERCUS PRINUS                       51
FRAXINUS AMERICANA                   51
PRUNUS CERASIFERA                    48
CEDRUS DEODARA                       48
PRUNUS PERSICA                       46
PINUS GLABRA                         45
PRUNUS SUBHIRTELLA                   38
SALIX BABYLONICA                     36
ERIOBOTRYA JAPONICA                  35
BETULA POPULIFOLIA                   35
HIBISCUS SYRIACUS                    32
CARYA SPECIES                        32
CUPRESSOCYPARIS LEYLANDII            32
POPULUS BALSAMIFERA                  29
THUJA OCCIDENTALIS                   28
MAGNOLIA STELLATA                    27
JUGLANS NIGRA                        25
FAGUS GRANDIFOLIA                    24
PRUNUS TRILOBA                       24
PINUS ECHINATA                       24
PINUS THUNBERGII                     24
ACER PENSYLVANICUM                   23
ACER NEGUNDO                         23
BETULA PENDULA                       22
ILEX OPACA                           22
UNKNOWN SHAFT                        22
QUERCUS COCCINEA                     22
CHAMAECYPARIS THYOIDES               21
ACER NIGRUM                          21
POPULUS CANESCENS                    20
QUERCUS VELUTINA                     20
JUNIPERUS VIRGINIANA                 20
BETULA PAPYRIFERA                    20
ACER CAMPESTRE                       18
ACER GINNALA                         17
BETULA NIGRA                         17
PRUNUS SARGENTII                     16
ALNUS GLUTINOSA                      16
SEQUOIA SEMPERVIRENS                 16
ARACAURIA EXCELSA                    16
PRUNUS PENNSYLVANICA                 16
GREVILLEA ROBUSTA                    16
MELIA AZEDARACH                      15
PHELLODENDRON AMURENSE               15
PLATANUS OCCIDENTALIS                15
QUERCUS ACUTISSIMA                   15
MAGNOLIA SOULANGIANA                 15
FAGUS SYLVATICA                      15
PRUNUS MAACKII                       14
CARPINUS CAROLINIANA                 13
PISTACIA CHINENSIS                   13
CORNUS KOUSA                         12
PICEA MARIANA                        12
POPULUS TREMULOIDES                  12
ZELKOVA SPECIES                      12
METASEQUOIA GLYPTOSTROBOIDES         11
CARYA TEXANA                         11
LARIX DECIDUA                        10
SHRUB                                10
ULMUS PUMILA                         10
PINUS RIGIDA                         10
HEDGE                                10
CERCIS CANADENSIS                    10
AMELANCHIER SPECIES                  10
SALIX NIGRA                           9
TAXODIUM DISTICHUM                    9
PINUS CLAUSA                          9
KOELREUTERIA PANICULATA               9
PAULOWNIA TOMENTOSA                   9
AMELANCHIER ARBOREA                   8
PINUS SEROTINA                        8
CARPINUS BETULUS                      8
ROSA SPECIES                          8
PALM SPECIES                          8
SEQUOIADENDRON GIGANTEA               8
PICEA GLAUCA                          7
TABEBUIA SPECIES                      7
ILEX CASSINE                          7
FRAXINUS BERLANDIERIANA               7
POPULUS GRANDIDENTATA                 7
FRAXINUS ORNUS                        7
POPULUS NIGRA                         7
PSEUDOTSUGA MENZIESII                 7
CELTIS LAEVIGATA                      6
QUERCUS VIRGINIANA                    6
ACACIA FARNESIANA                     6
POPULUS TRICHOCARPA                   6
ELAEAGNUS UMBELLATA                   6
LONICERA SPECIES                      6
CARYA TOMENTOSA                       6
PRUNUS VIRGINIANA                     6
CASTANEA MOLLISSIMA                   5
ULMUS SEROTINA                        5
CRYPTOMERIA JAPONICA                  5
MYRICA CERIFERA                       5
ULMUS ALATA                           5
GYMNOCLADUS DIOICUS                   5
BETULA LENTA                          5
SORBUS AUCUPARIA                      5
ACACIA AURICULAEFORMIS                5
MYRICA HETEROPHYLLA                   5
ABIES BALSAMEA                        5
SAPIUM SEBIFERUM                      4
QUERCUS SCHUMARDII                    4
SALIX MATSUDANA                       4
FICUS BENJAMINA                       4
QUERCUS MARILANDICA                   4
CARYA LACINIOSA                       4
MAGNOLIA DENUDATA                     4
CARYA CORDIFORMIS                     4
CINNAMOMUM CAMPHORA                   3
HIBISCUS SPECIES                      3
ABIES CONCOLOR                        3
CASTANEA PUMILA                       3
JUGLANS REGIA                         3
PINUS BANKSIANA                       3
ACER BUERGERANUM                      3
ELAEAGNUS ANGUSTIFOLIA                3
PERSEA BORBONIA                       3
ULMUS PROCERA                         3
CARYA GLABRA                          3
JUGLANS CINEREA                       3
SORBUS AMERICANA                      3
ULMUS CRASSIFOLIA                     3
MAGNOLIA GRANDIFLORA                  2
FIRMIANA SIMPLEX                      2
AESCULUS GLABRA                       2
QUERCUS STELLATA                      2
ULMUS RUBRA                           2
LIGUSTRUM LUCIDUM                     2
QUERCUS BICOLOR                       2
PRUNUS ARMENIACA                      2
PRUNUS AVIUM                          2
VIBURNUM TRILOBUM                     2
BROUSSONETIA PAPYRIFERA               2
FICUS RUBIGINOSA                      2
ASIMINA TRILOBA                       2
ARBORVITAE PLICATA                    2
ARAUCARIA ARAUCANA                    2
CRATAEGUS VIRIDIS                     2
ULMUS THOMASII                        2
CASUARINA EQUISETIFOLIA               2
POPULUS HETEROPHYLLA                  2
AESCULUS OCTANDRA                     2
PRUNUS CAROLINIANA                    2
LIGUSTRUM SPECIES                     1
CRATAEGUS CRUS-GALLI                  1
QUERCUS AUSTRINA                      1
ACOELORRHAPHE WRIGHTII                1
QUERCUS LYRATA                        1
HAMAMELIS VIRGINIANA                  1
CERCIDIPHYLLUM JAPONICUM              1
DIOSPYROS VIRGINIANA                  1
QUERCUS MUEHLENBERGII                 1
PHOENIX CANARIENSIS                   1
CLADRASTIS LUTEA                      1
CORYLUS SPECIES                       1
PLUMERIA RUBRA                        1
QUERCUS FALCATA                       1
BRASSAIA ACTINOPHYLLA                 1
FRAXINUS QUADRANGULATA                1
SALIX PENTANDRA                       1
OXYDENDRUM ARBOREUM                   1
BETULA ALLEGHANIENSIS                 1
CALLISTEMON PENDULA                   1
LABURNUM WATERERI                     1
KOELREUTERIA ELEGANS                  1
FICUS AUREA                           1
PINUS RESINOSA                        1
CARYA OVATA                           1
BISCHOFIA JAVONICA                    1
SYZYGIUM CUMINI                       1
QUERCUS INCANA                        1
QUERCUS MACROCARPA                    1
CONOCARPUS SERICEIUS                  1
PONGAMIA PINNATA                      1
SABAL PALMETTO                        1
COTINUS COGGYGRIA                     1
POPULUS ALBA                          1
FRAXINUS EXCELSIOR                    1
THUJA ORIENTALIS                      1
FICUS CARICA                          1
PINUS SYLVESTRIS                      1
CRATAEGUS MARSHALLII                  1

In [55]:
df_95_bk = df_95[df_95.Borough == 'Brooklyn']

In [38]:
species_95_bk = list(df_95_bk.Spc_Common.unique())

In [39]:
len(species_95_bk)

187

In [40]:
df_95_bx = df_95[df_95.Borough == 'Bronx']

In [41]:
species_95_bx = list(df_95_bx.Spc_Common.unique())

In [42]:
len(species_95_bx)

148

In [44]:
df_95_si = df_95[df_95.Borough == 'Staten Island']

In [45]:
species_95_si = list(df_95_si.Spc_Common.unique())

In [46]:
len(species_95_si)

126

In [47]:
df_95_qn = df_95[df_95.Borough == 'Queens']

In [48]:
species_95_qn = list(df_95_qn.Spc_Common.unique())

In [49]:
len(species_95_qn)

178

In [52]:
df_95_mn = df_95[df_95.Borough == 'Manhattan']

In [53]:
species_95_mn = list(df_95_mn.Spc_Common.unique())

In [54]:
len(species_95_mn)

85

In [ ]:
## Trees 2005

In [10]:
df_05.head(2)

,OBJECTID,cen_year,tree_dbh,address,tree_loc,pit_type,soil_lvl,status,spc_latin,spc_common,vert_other,vert_pgrd,vert_tgrd,vert_wall,horz_blck,horz_grate,horz_plant,horz_other,sidw_crack,sidw_raise,wire_htap,wire_prime,wire_2nd,wire_other,inf_canopy,inf_guard,inf_wires,inf_paving,inf_outlet,inf_shoes,inf_lights,inf_other,trunk_dmg,zipcode,zip_city,cb_num,borocode,boroname,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,objectid_1,census tract,bin,bbl,Location 1
0,592373,2005,6,1139 57 STREET,Front,Sidewalk Pit,Level,Good,PYRUS CALLERYANA,"PEAR, CALLERY",No,No,No,No,No,No,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,None,11219,Brooklyn,312,3,Brooklyn,44,48,17,BK88,Borough Park,3021600.0,New York,40.632653,-74.000245,984182,169769,0,216.0,3140038.0,3.056890e+09,"(40.63265321, -74.00024499)"
1,592374,2005,6,2220 BERGEN AVENUE,Across,Sidewalk Pit,Level,Good,PLATANUS ACERIFOLIA,LONDON PLANETREE,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,None,11234,Brooklyn,318,3,Brooklyn,46,59,19,BK45,Georgetown-Marine Park-Bergen Beach-Mill Basin,3070600.0,New York,40.620084,-73.901453,1011608,165205,1,706.0,3238037.0,3.084440e+09,"(40.62008375, -73.9014528)"

In [58]:
df_05.boroname.unique()

array(['Brooklyn', 'Manhattan', 'Bronx', 'Queens', '5', 5], dtype=object)

In [11]:
df_05.spc_common.unique()

array(['PEAR, CALLERY', 'LONDON PLANETREE', 'MAPLE, NORWAY-CR KNG',
       'HAWTHORN, OTHER', 'MAPLE, NORWAY', 'HONEYLOCUST',
       'LINDEN, LITTLE LEAF', 'UNKNOWN', 'GINKGO', 'GOLDENRAIN TREE',
       'DOGWOOD, FLOWERING', 'MAPLE, SYCAMORE', 'MAPLE, RED',
       'PLUM, PURPLELEAF', 'ZELKOVA, JAPANESE', 'OAK, PIN', 'ASH, GREEN',
       'JAPANESE TREE LILAC', 'CHERRY, OTHER', 'MAPLE, AMUR',
       'JAPANESE PAGODA TREE', 'KATSURA TREE', 'OAK, NORTHERN RED',
       'Unknown Dead', 'ELM, AMERICAN', 'ELM, CHINESE', 'LINDEN, SILVER',
       'OAK, WHITE', 'LINDEN, AMERICAN', 'OAK, SWAMP WHITE',
       'TREE OF HEAVEN', 'DAWN REDWOOD', 'OAK, SAWTOOTH', 'BLACK LOCUST',
       'OAK, WILLOW', 'HORNBEAM, AMERICAN', 'REDBUD, EASTERN',
       'KENTUCKY COFFEETREE', 'CHOKECHERRY, SHUBERT', 'MAPLE, SILVER',
       'HACKBERRY', 'BALDCYPRESS', 'HORNBEAM, EUROPEAN', 'POPLAR, OTHER',
       'MAPLE, HEDGE', 'MULBERRY', 'ELM, OTHER', 'MAPLE, JAPANESE',
       'MAGNOLIA, OTHER', 'CRABAPPLE', 'OAK, OTHER', 'ELM, SIBERIAN',
       'SWEETGUM', 'OAK, LAUREL', 'HOLLY SPECIES', 'OAK, ENGLISH',
       'TULIP TREE', 'CHERRY, KWANZAN', 'LINDEN, OTHER', 'BIRCH, OTHER',
       'MAPLE, OTHER', 'HORSECHESTNUT', 'PINE, JAPANESE BLACK',
       'MAPLE, SUGAR', 'PINE, EASTERN WHITE', 'PINE, OTHER',
       'DOGWOOD, KOUSA', 'SPRUCE, OTHER', 'BOXELDER',
       'SERVICEBERRY, OTHER', 'HEMLOCK, EASTERN', 'OAK, TURKEY', 'APPLE',
       'OAK, BUR', 'PERSIMMON, COMMON', 'HICKORY', 'YELLOWOOD',
       'WILLOW SPECIES', 'OAK, SCARLET', 'ASH, OTHER', 'SILVERBELL',
       'BEECH, AMERICAN', 'ASH, WHITE', 'DOUGLAS FIR',
       'SNOWBELL, JAPANESE', 'SPRUCE, COLORADO', 'ELM, ENGLISH',
       'PINE, RED', 'CEDAR, ATLAS', 'EASTERN REDCEDAR',
       'ARBORVITAE, EASTERN', 'CATALPA', 'SPRUCE, NORWAY',
       'CHESTNUT, CHINESE', 'HARDY RUBBER TREE', 'PEACH TREE',
       'COMMON PEAR', 'CHERRY, BLACK', 'BLACKGUM', 'ALDER, EUROPEAN',
       'POPLAR, LOMBARDY', 'COTTONWOOD, EASTERN', 'OAK, SOUTHERN RED',
       'ELM, SLIPPERY', 'AMUR CORKTREE', 'MIMOSA', 'DOGWOOD SPP.',
       'MAPLE, TRIDENT', 'OAK, SHINGLE', 'PINE, VIRGINIA',
       'WALNUT, BLACK', 'DROOPING JUNIPER', 'PINE, SHORTLEAF',
       'PINE, AUSTRIAN', 'WITCH HAZEL', 'BEECH, EUROPEAN',
       'HORSECHESTNUT, RED', 'ROYAL PAULOWNIA', 'MAACKIA,AMUR',
       'WEEPING WILLOW', 'LARCH', 'MOUNTAINASH, AMERICAN',
       'MAGNOLIA, SOUTHERN', 'OSAGE-ORANGE', 'SASSAFRAS',
       'BIRCH, EUROPEAN WHITE', 'CHERRY, CORNELIAN', 'GOLDEN-CHAIN TREE',
       'MAPLE, PAPERBACK', 'EASTERN HOP HORNBEAM', 'BIRCH, PAPER',
       'TAMARACK', 'DOGWOOD, SILKY', 'ELM, ROCK', 'OAK, BLACK',
       'OHIO BUCKEYE', 'SOURWOOD', 'PONDCYPRESS', 'BIRCH, RIVER',
       'PINE, SCOTCH', 'OAK, POST', 'JUNIPER SPP.', 'QUAKING ASPEN',
       'CORKSCREW WILLOW', 'CAROLINA SILVERBELL', 'MAPLE, TATARIAN',
       'MAPLE, BLACK', 'TURKISH HAZELNUT', 'PINE, PITCH',
       'ATLANTIC WHITECEDAR', 'BIRCH, YELLOW', 'CUCUMBER TREE',
       'BALDCYPRESS SPECIES', 'PECAN', 'ELM, WINGED',
       'DOGWOOD, ALTERNATE-LEAVED', 'HICKORY, PIGNUT', 'ASPEN, BIGTOOTH',
       'WILLOW ?', 'RUSSIAN OLIVE', 'FIR, BALSAM', 'FIR, WHITE',
       'PINE, MUGO', 'AMERICAN SMOKETREE', 'CHESTNUT, AMERICAN',
       'MOUNTAINASH, KOREAN', 'FALSECYPRESS, JAPANESE', 'CEDAR, DEODAR',
       'HICKORY, SHAGBARK'], dtype=object)

In [17]:
acn_sn = df_05.drop_duplicates('spc_common')

In [18]:
acn_sn.head()

,OBJECTID,cen_year,tree_dbh,address,tree_loc,pit_type,soil_lvl,status,spc_latin,spc_common,vert_other,vert_pgrd,vert_tgrd,vert_wall,horz_blck,horz_grate,horz_plant,horz_other,sidw_crack,sidw_raise,wire_htap,wire_prime,wire_2nd,wire_other,inf_canopy,inf_guard,inf_wires,inf_paving,inf_outlet,inf_shoes,inf_lights,inf_other,trunk_dmg,zipcode,zip_city,cb_num,borocode,boroname,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,objectid_1,census tract,bin,bbl,Location 1
0,592373,2005,6,1139 57 STREET,Front,Sidewalk Pit,Level,Good,PYRUS CALLERYANA,"PEAR, CALLERY",No,No,No,No,No,No,Yes,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,None,11219,Brooklyn,312,3,Brooklyn,44,48,17,BK88,Borough Park,3021600.0,New York,40.632653,-74.000245,984182,169769,0,216.0,3140038.0,3.056890e+09,"(40.63265321, -74.00024499)"
1,592374,2005,6,2220 BERGEN AVENUE,Across,Sidewalk Pit,Level,Good,PLATANUS ACERIFOLIA,LONDON PLANETREE,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,None,11234,Brooklyn,318,3,Brooklyn,46,59,19,BK45,Georgetown-Marine Park-Bergen Beach-Mill Basin,3070600.0,New York,40.620084,-73.901453,1011608,165205,1,706.0,3238037.0,3.084440e+09,"(40.62008375, -73.9014528)"
2,592375,2005,13,2360 BERGEN AVENUE,Front,Continuous Pit,Level,Good,ACER PLATANOIDES CRIMSON KING,"MAPLE, NORWAY-CR KNG",No,No,No,No,No,No,Yes,Yes,No,No,Yes,Yes,Yes,No,No,No,No,Yes,No,No,No,Yes,Cavity,11234,Brooklyn,318,3,Brooklyn,46,59,19,BK45,Georgetown-Marine Park-Bergen Beach-Mill Basin,3070600.0,New York,40.617996,-73.899111,1012259,164445,2,706.0,3238299.0,3.084530e+09,"(40.61799567, -73.89911096)"
9,592382,2005,3,1163 57 STREET,Front,Lawn,Level,Good,CRATAEGUS SPECIES,"HAWTHORN, OTHER",No,Yes,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,None,11219,Brooklyn,312,3,Brooklyn,44,48,17,BK88,Borough Park,3021600.0,New York,40.632423,-73.999867,984287,169685,9,216.0,3140034.0,3.056890e+09,"(40.63242265, -73.9998667)"
14,592387,2006,10,5702 12 AVENUE,Side,Sidewalk Pit,Level,Poor,ACER PLATANOIDES,"MAPLE, NORWAY",No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,None,11219,Brooklyn,312,3,Brooklyn,44,48,17,BK88,Borough Park,3021600.0,New York,40.631786,-73.999085,984504,169453,14,216.0,3140347.0,3.056960e+09,"(40.63178585, -73.9990849)"

In [19]:
acn_sn = acn_sn[['spc_common', 'spc_latin']]

In [20]:
acn_sn.to_csv(r'species_asis_05.csv')

In [15]:
unique_05 = pd.DataFrame(df_05['spc_common'].unique())

In [16]:
unique_05.shape

(169, 1)

In [ ]:
spc_latin

In [61]:
df_05_bk = df_05[df_05.boroname == 'Brooklyn']

In [62]:
species_05_bk = list(df_05_bk.spc_common.unique())

In [63]:
len(species_05_bk)

140

In [74]:
df_05_si = df_05[(df_05.boroname == '5') | (df_05.boroname == 5)]

In [75]:
species_05_si = list(df_05_si.spc_common.unique())

In [76]:
len(species_05_si)

134

In [86]:
df_05_bx = df_05[df_05.boroname == 'Bronx']

In [82]:
species_05_bx = list(df_05_bx.spc_common.unique())

In [83]:
len(species_05_bx)

121

In [85]:
df_05_qn = df_05[df_05.boroname == 'Queens']

In [87]:
species_05_qn = list(df_05_qn.spc_common.unique())

In [88]:
len(species_05_qn)

157

In [89]:
df_05_mn = df_05[df_05.boroname == 'Manhattan']

In [90]:
species_05_mn = list(df_05_mn.spc_common.unique())

In [91]:
len(species_05_mn)

91

In [ ]:
## Trees 2015

In [30]:
df_15.head(4)

,created_at,tree_id,block_id,the_geom,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,steward,guards,sidewalk,user_type,problems,root_stone,root_grate,root_other,trnk_wire,trnk_light,trnk_other,brnch_ligh,brnch_shoe,brnch_othe,address,zipcode,zip_city,cb_num,borocode,boroname,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,Latitude,longitude,x_sp,y_sp
0,08/27/2015,180683,348711,POINT (-73.84421521958048 40.723091773924274),3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,None,None,NoDamage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,108-005 70 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,4073900,New York,40.723092,-73.844215,1.027431e+06,202756.768749
1,09/03/2015,200540,315986,POINT (-73.81867945834878 40.79411066708779),21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,147-074 7 AVENUE,11357,Whitestone,407,4,Queens,19,27,11,QN49,Whitestone,4097300,New York,40.794111,-73.818679,1.034456e+06,228644.837379
2,09/05/2015,204026,218365,POINT (-73.93660770459083 40.717580740099116),3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,1or2,None,Damage,Volunteer,None,No,No,No,No,No,No,No,No,No,390 MORGAN AVENUE,11211,Brooklyn,301,3,Brooklyn,34,50,18,BK90,East Williamsburg,3044900,New York,40.717581,-73.936608,1.001823e+06,200716.891267
3,09/05/2015,204337,217969,POINT (-73.93445615919741 40.713537494833226),10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,None,None,Damage,Volunteer,Stones,Yes,No,No,No,No,No,No,No,No,1027 GRAND STREET,11211,Brooklyn,301,3,Brooklyn,34,53,18,BK90,East Williamsburg,3044900,New York,40.713537,-73.934456,1.002420e+06,199244.253136

In [102]:
len(df_15)

683788

In [92]:
df_15.boroname.unique()

array(['Queens', 'Brooklyn', 'Manhattan', 'Staten Island', 'Bronx'],
      dtype=object)

In [104]:
df_15_bk = df_15[df_15.boroname == 'Brooklyn']

In [105]:
species_15_bk = list(df_15_bk.spc_common.unique())

In [106]:
len(species_15_bk)

133

In [107]:
df_15_bx = df_15[df_15.boroname == 'Bronx']

In [108]:
species_15_bx = list(df_15_bx.spc_common.unique())

In [109]:
len(species_15_bx)

133

In [99]:
df_15_qn = df_15[df_15.boroname == 'Queens']

In [100]:
species_15_qn = list(df_15_qn.spc_common.unique())

In [101]:
len(species_15_qn)

133

In [110]:
df_15_mn = df_15[df_15.boroname == 'Manhattan']

In [111]:
species_15_mn = list(df_15_mn.spc_common.unique())

In [112]:
len(species_15_mn)

129

In [113]:
df_15_si = df_15[df_15.boroname == 'Staten Island']

In [114]:
species_15_si = list(df_15_si.spc_common.unique())

In [115]:
len(species_15_si)

132

In [26]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})

In [27]:
df.head()

   A  B  C
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [28]:
df = df.replace(0, 5)

In [29]:
df.head()

   A  B  C
0  5  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [31]:
df = df.replace({'e': 10, 1: 100})

In [32]:
df.head()

     A  B   C
0    5  5   a
1  100  6   b
2    2  7   c
3    3  8   d
4    4  9  10